### ISSUE TITLE
Enviar propuesta a Japan Media Arts Festival

### ISSUE THREAD

**Issue by thiagohersan** [astrovandalistas/Astrofuturismo#7]
http://festival.j-mediaarts.jp/en/entry/entry-guidelines/

**Comment by bichiento** [comment]
Qué crees que le haga falta al video que tenemos para usarlo para la aplicación?

**Comment by thiagohersan** [comment]
Por ahora creo que no hay que hacer nada con el video.
Envié un proyecto en 2012 y había que enviar solo un video con todo.
Ahora, aceptan sitios. Voy enviar http://futureglyphs.astrovandalistas.cc/.

Podemos actualizar el video en vimeo con el audio track después.

**Comment by thiagohersan** [comment]
<img width="635" alt="jmaf_2017" src="https://user-images.githubusercontent.com/850815/29879810-8977ae44-8d7c-11e7-82c9-1c1d50e3453f.png">
